spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://anoopyadav5984:wswR1xQYruNiwCq5@cluster0.flfbzgv.mongodb.net/testdb?retryWrites=true&w=majority
spring.mongodb.uri=mongodb+srv://anoopyadav5984:wswR1xQYruNiwCq5@cluster0.flfbzgv.mongodb.net/testdb?retryWrites=true&w=majority
spring.data.mongodb.auto-index-creation=true

jwt.secret=7A3F68C9B5D4E12F8A4B69C2D8E37F15A0C5B9D2E6F4A8B3C7D1E9F0A2B5C8D4
jwt.expiration=86400000

llm.api.key=AIzaSyD3_mhg4vMXs8IcOip19ppso_rn4nkmZ0M
grok.api.key=YOUR_GROK_API_KEY_HERE
